site_centos: IK_centos.sa
site_debian: IK_debian.sa
nginx_config_path: /etc/nginx/conf.d/

centos_home_path: /usr/share/nginx/html
debian_host_path: /var/www/html

virtual_domain:
  - { name: "{{ site_centos }}", ip: "{{ hostvars[\"w_1\"].ansible_host }}"}
  - { name: "{{ site_debian }}", ip: "{{ hostvars[\"w_2\"].ansible_host }}"}
