---
- name: Include deploy for Debian systems
  include: http_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat systems
  include: http_RedHat.yaml
  when: ansible_os_family == 'RedHat'
- name: Copy first page
  copy:
    src: index.html
    dest: "{{ default_home }}"
    owner: root
    group: root
    mode: '0775'
  notify:
    - restart apache
