---
- name: include deploy for Debian systems
  include: nginx_debian.yml
  when: ansible_os_family == 'Debian'

- name: include deploy for RedHat systems
  include: nginx_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: template
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: yes

- name: check connection to localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3

- name: check site content
  uri:
    url: http://localhost
    return_content: yes
  register: this
  
- name: print out
  debug:
    msg: "{{ out }}"

- name: Templates
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: '0644'
    backup: yes

