---
- name: Install nginx
  apt:
        name=nginx
        state=latest
- name: Delete default nginx vhost
  file:
        path={{ nginx_sites }}/default
        state=absent

- name: Delete default nginx vhost symlink
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Setup nginx vhost
  template:
        src=nginx.tpl
        dest={{ nginx_sites }}/{{ conf_file }}.conf

- name: Create symlink nginx vhost
  file:
        src={{ nginx_sites }}/{{ conf_file }}.conf
        dest=/etc/nginx/sites-enabled/{{ conf_file }}.conf
        state=link
  notify: restart nginx

