---
all:
  children:
    w:
      hosts:
        worker_centos:
          ansible_host: 192.168.202.9
        worker_ubuntu:
          ansible_host: 192.168.202.10
    k8s:
      vars: 
        data: 1
      hosts:
        master:
          ansible_host: 192.168.203.9
        slave:
          ansible_host: 192.168.203.10
