---
- hosts: ec2
  # gather_facts: False
  # strategy: free
  # serial: 1
  vars:
    var_01: "Hi"
    var_02: True
    var_03: 42
  pre_tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ item }}"
      with_items:
      - "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
  tasks:
    - name: Print variables 
      debug:
        msg: "{{ var_01 }} | {{ var_02 }} | {{ var_03 }}"
      tags:
        - local_vars
    - name: Print facts 1
      debug:
        msg: "{{ ansible_facts.mounts[0].size_available }}"
      tags:
        - remote_vars
    - name: Print facts 2
      debug:
        msg: "{{ ansible_distribution }} | {{ ansible_distribution_version }}"
      tags:
        - remote_vars
    - name: Debug
      debug:
        msg: "Hi from {{ inventory_hostname }}"
    - name: Debug
      debug:
        msg: "{{ hostvars[inventory_hostname].env }}  || {{ env }}" 
