---
- hosts: ec
  vars:
    user: IKorolev
  tasks:
    - name: Creating user {{ user }}
      user:
        name: "{{ user }}"
        state: present
    - name: Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: 'Match User {{ user }} PasswordAuthentication no'
        insertbefore: BOF

    - name: Install sudo on Centos
      when: ansible_distribution == 'CentOS'
      shell: |
        yum install sudo -y      
      register: out
    - debug:
        msg: "{{ out.stdout_lines }}"
      when: ansible_distribution == 'CentOS'

    - name: Add {{ user }} for upgrade command
      when: ansible_distribution == 'CentOS'
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
        insertbefore: BOF

    - name: Add {{ user }} for upgrade command
      when: ansible_distribution == 'Ubuntu'
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
        insertbefore: BOF

    - name: Check user
      shell: |
        grep "{{ user }}" /etc/passwd
      register: out
    - debug:
        msg: "{{ out.stdout_lines }}"

    - name: System upgrade by {{ user }}
      remote_user: "{{ user }}"
      when: ansible_distribution == 'CentOS'
      shell: |
        sudo yum upgrade -y
      register: out
    - debug:
        msg: "{{ out.stdout_lines }}"
      when: ansible_distribution == 'CentOS'

    - name: System upgrade by {{ user }}
      remote_user: "{{ user }}"
      when: ansible_distribution == 'Ubuntu'
      shell: |
        sudo apt upgrade -y     
      register: out
    - debug:
        msg: "{{ out.stdout_lines }}"
      when: ansible_distribution == 'Ubuntu'
