---
yum_nginx_packages:
  - nginx

apt_nginx_packages:
  - nginx

default_home_debian: "/var/www/html/"
default_home_redhat: "/usr/share/nginx/html/"
virtual_hosts:
  - { name: "centos_nginx.site", ip: "{{ hostvars[\"centos_9\"].ansible_host }}"}
  - { name: "ubuntu_nginx.site", ip: "{{ hostvars[\"ubuntu_10\"].ansible_host }}"}
