---
- name: Include deploy for Debian systems
  include: http_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat systems
  include: http_RedHat.yaml
  when: ansible_os_family == 'RedHat'
