---
- name: Update and Install
  apt: update_cache=yes name=nginx

- name: install nginx
  yum:
    name: nginx
    state: present
    update_cache: yes
- name: create folders
  file:
    path: '/etc/nginx/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - conf-available
    - sites-available
    - sites-enabled
- name: Copy nginx config
  template:
    src: debian.conf.j2
    dest: "{{ nginx_config_path }}"
  notify:
    - restart nginx

- name: Copy index.html Debian
  copy:
    src: index.html
    dest: "{{ debian_host_path }}"
