---
- name: Redmine. Setup 01
  shell: |
    gem install bundler
    bundle update   
  args:
    executable: /bin/bash
    chdir: "{{ app_home }}"
  tags: 
    - setup
- name: Session store secret generation
  shell: rake generate_secret_token
  args:
   chdir: "{{ app_home }}"
   creates: "{{ app_home }}/config/initializers/secret_token.rb"
  tags:
    - setup
- name: Redmine. Setup 02
  shell: | 
    bundle exec rake db:migrate RAILS_ENV=production 
    bundle exec rake redmine:plugins:migrate RAILS_ENV=production
    bundle install --without development test
    RAILS_ENV=production rake db:migrate
    #RAILS_ENV=production REDMINE_LANG="{{ app_lang }}" rake redmine:load_default_data
    #bundle exec rails server webrick -e production
  args:
    chdir: "{{ app_home }}"
  tags:
    - setup
    
- name: Update and Install
  apt: update_cache=yes name=nginx

- name: Nginx. Enable ans start
  systemd:
    name: nginx
    state: started
    
- name: Configuration files for virtualhost
  template:
    src: redmine.site.conf.j2
    dest: "/etc/nginx/sites-available/redmine.site.conf"
  notify:
    - nginx restart 
